Blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('',views.HomePageView.as_view(),name='home'),
	path('postDetail/<slug:slug>/',views.PostDetailView.as_view(),name='detail'),

]

personalBlogging/urls.py
from django.contrib import admin
from django.urls import path,include
from Blog import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.


class Post(models.Model):

	post_image = models.TextField()

	post_title = models.CharField(max_length=200)

	post_date = models.DateTimeField(auto_now_add=True)

	post_auther = models.CharField(max_length=100)

	post_content = RichTextField(blank=True,null=True)

	slug = models.SlugField(null=False,unique=True)

	#some sorts of string representation in the admin site
	def __str__(self):
		return self.post_title

	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'slug':self.slug})



    # def get_absolute_url(self):
    #     return reverse("posts:detail", kwargs={"slug": self.post_slug})

Blog/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
# Create your views here.

#homepage view
class HomePageView(ListView):
	model = Post
	template_name = 'Blog/index.html'
	context_object_name = 'post_entries'
	ordering = ('-post_date')
	paginate_by = 5


	#sidebar view
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		side_view = Post.objects.all().order_by('-post_date')[0:5]
		context['side_view'] = side_view
		return context




class PostDetailView(DetailView):
	model = Post
	template_name = 'Blog/post_detail.html'
	context_object_name = 'post_detail'
	slug_url_kwarg = 'slug'

	#sidebar view
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		side_view = Post.objects.all().order_by('-post_date')[0:5]
		context['side_view'] = side_view
		return context


	

Blog/templates/Blog/index.html
{% extends 'base.html' %}


{% block title %}Real Life Blog{% endblock %}



{% block blogcontents %}

	{% if post_entries %}
		{% for posts in post_entries %}
			<div class="card mt-5">	
				<div class="card-body">
					<h1 class="title mt-2">{{ posts.post_title }}</h1>
					<p class="user-detail mt-4"><i class="fas fa-user-astronaut mr-2"></i>{{ posts.post_auther }} | {{ posts.post_date|date }}</p> <br>

					<img class="ml-4" src="{{ posts.post_image }}" height="auto" width="80%">
					<p class="mt-4">{{ posts.post_content|safe|truncatechars:150 }}</p>

					<a href="{% url 'blog:detail' slug=posts.slug %}"><input type="submit" value="Read more" class="btn btn-primary readmore mt-2"></a>
				</div>
			</div>
		{% endfor %}
	{% endif %}


	{% if is_paginated %}
<!-- Pagination -->
    	<ul class=" pagination justify-content-center mb-4 mt-5">
    	{% if page_obj.has_previous  %}	
     		<li class="page-item">
        		<a class="page-link paginate" href="?page={{ page_obj.previous_page_number }}">&larr; Previous Page</a>
      		</li>
      	{% endif %}	

      	{% if page_obj.has_next %}
      		<li class="page-item">
        		<a class="page-link paginate" href="?page={{ page_obj.next_page_number }}">Next Page &rarr;</a>
      		</li>
      	{% endif %}
    	</ul>
    {% endif %}

{% endblock %}




{% block sidebar %}
		{% if side_view %}
			<div class="list-group border border-white mt-5 ml-2">
				<input type="button" class="list-group-item button-effect" value="Recent posts">
				{% for views in side_view %}
					<a class="nav-link" href="{% url 'blog:detail' slug=views.slug %}">  
					   <button type="button" class="list-group-item list-group-item-action"><img class="rounded-circle" src="{{ views.post_image }}" height="50px" width="50px"><p class="ml-1"><b>{{ views.post_title }}</b></p></button>
					</a>
				{% endfor %}				
			</div>

		{% endif %}



{% endblock %}

Blog/templates/Blog/post_detail.html
{% extends 'base.html' %}

{% block title %}{{post_detail.post_title}}{% endblock %}

{% block blogcontents %}

	<div class="card mt-5">	
		<div class="card-body">
			<h1 class="title mt-2">{{ post_detail.post_title }}</h1>
			<p class="user-detail mt-4"><i class="fas fa-user-astronaut mr-2"></i>{{ post_detail.post_auther }} | {{ post_detail.post_date|date }}</p> <br>

			<img class="ml-4" src="{{ post_detail.post_image }}" height="auto" width="80%">
			<p class="mt-4">{{ post_detail.post_content|safe|linebreaks }}</p>
		</div>
	</div>

{% endblock %}


{% block sidebar %}
		{% if side_view %}
			<div class="list-group border border-white mt-5 ml-2">
				<input type="button" class="list-group-item button-effect" value="Recent posts">
				{% for views in side_view %}
					<a class="nav-link" href="{% url 'blog:detail' slug=views.slug %}">  
					   <button type="button" class="list-group-item list-group-item-action"><img class="rounded-circle" src="{{ views.post_image }}" height="50px" width="50px"><p class="ml-1"><b>{{ views.post_title }}</b></p></button>
					</a>
				{% endfor %}				
			</div>

		{% endif %}


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{% block title %}{% endblock %}</title>

  <!-- bootstrapcd -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- font awesome -->
  <script src="https://kit.fontawesome.com/5ce813b2e5.js" crossorigin="anonymous"></script>


<!-- some meta tags for responsive experience -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  


  <!-- javascripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  <!-- my css files -->
  <link rel="stylesheet" type="text/css" href="{% static 'Blog/css/main.css' %}">

  <!-- font -->
  <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Amaranth&display=swap" rel="stylesheet">
 
  <!-- adsence -->
   <script data-ad-client="ca-pub-2379582731794113" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>


</head>
<body class="bg">
  <nav class="navbar navbar-light justify-content-left">
    <a class="navbar-brand" href="{% url 'blog:home' %}"><img src="{% static 'Blog/images/reallifeblogging.png' %}"></a>

    <ul class="navbar-nav social-icons">
      <li class="nav-item">
        <a class="nav-link" href="https://www.facebook.com/aashish.upadhyay.3760"><i class="fab fa-facebook"> Facebook</i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.instagram.com/aashiish_upadhyay/"><i class="fab fa-instagram"> Instagram</i></a>
      </li>
    </ul>
    
  </nav>


  <nav class="navbar sticky-top navbar-expand-sm mynav justify-content-right">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fas fa-bars"> Menu</i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link mr-4 text-white" href="{% url 'blog:home' %}">Home</a>
        </li>

        <li class="nav-item textcolor">
          <a class="nav-link mr-4 text-white" href="#About">About Me</a>
        </li>

        <li class="nav-item textcolor">
          <a class="nav-link text-white"  href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- main container and body of the blog -->
  <div class="container">
    <!-- google ads --> 


    <div class="row">
      <div class="col-sm-1">
        <!-- empty -->
      </div>
      <div class="col-sm-7">
        
        {% block blogcontents %}{% endblock %}




<hr id="form-location" class="border">
<hr class="border">
<hr>
<hr>
<hr>

<!-- about me side -->
  <div class="container">
    <h1 class="title mt-5" id="About">About Me:</h1>
    <img src="https://scontent.fktm8-1.fna.fbcdn.net/v/t1.0-1/c0.0.160.160a/p160x160/67608284_844391495961354_7116495376198139904_o.jpg?_nc_cat=109&_nc_ohc=IIVavLExEB4AQlzWhno_jvcT5XpWMAh3TW8uf5JVVCGeYDCj4bU808ouw&_nc_ht=scontent.fktm8-1.fna&oh=1cc5b85ab9dccd18aaa1f5036e0d2da0&oe=5E8A5ED4" class="rounded-circle justify-content-center" alt="Cinque Terre">

    <h3 class="mt-3">I'm a self taught software developer. I'm currently studying in high school with science background. I was influenced in programming when I was studying in grade 10.
      I just love coding. <br><hr>
    Coding is the thing that make me feel so good. When I look at these beautiful codes I felt like this is my world. <br><hr>
    I was always currious how the things work in reality. That makes my passion so strong, I want to explore the world of programming and want to make some unforgotable impact, and I'm trying to do so...
    </h3>

  </div>




        <div class="container mt-5">
          <h2 class="title" id="contact">Contact me</h2>
            <h3>My email: aashish.upadhyay949@gmail.com</h3>
        </div>

      </div>

      <!-- sidebar -->
      <div class="col-sm-4">
        <!-- google ads -->

        
        {% block sidebar %}{% endblock %}

        <!-- google ads -->

      </div>
    </div>
  </div>




<div class="footerline social-icons mt-4">
  <h3>Follow me on:</h3>
  <a href="https://www.facebook.com/aashish.upadhyay.3760">
    <i class="fab fa-facebook"></i>
  </a>
  <a href="https://www.instagram.com/aashiish_upadhyay/">
    <i class="fab fa-instagram"></i>
  </a>
</div>




<!-- contact form -->




<nav class="navbar mynav text mt-4 justify-content-center">
  <p>&copy; Copyright 2019<p>
</nav>


<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5dd90b7d797e56bd"></script>



</body>
</html>